accounts/urls.py
from django.urls import path
from .views import signupclass
from .views import ProfileDisplay
#from .views import logoutConfirmation
app_name = 'accounts'

urlpatterns = [
    path('signup/',signupclass.as_view(),name = 'signup_view'),
    path('profile/',ProfileDisplay.as_view() , name = 'Profile_view'),
    #path('logout_confirmation/',logoutConfirmation.as_view(), name = 'logout_confirmation'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from stories.views import Home_View

#app_name='stories_ref'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home_View,name = "Home_ref"),
    path('stories/', include('stories.urls',namespace='stories'),name = "stories_ref"),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('accounts/', include('accounts.urls')),  # new

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stories/urls.py
from .views import stories_view
from .views import share_view
from .views import blog_number
from django.urls import path
from .views import CreateBlog
#from django.conf.urls import url
app_name = 'stories'
urlpatterns = [
    path('', stories_view , name = "stories_home_ref"),
    path('share/',share_view, name = "share_ref"),
    path('<int:number>',blog_number, name = "blog_number_ref"),
    path('create/',CreateBlog.as_view(),name = "CreateBlog_ref")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Display_Picture = models.ImageField(upload_to='pictures',default="/pictures/pict.jpg")

    def __str__(self):
        return self.user.username

@receiver(signal=post_save,sender = User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user = instance)

stories/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class stories(models.Model):
    title      = models.CharField(max_length=50,null=False)
    description = models.CharField(max_length=50)
    content    = models.TextField(max_length=100000)
    comments   = models.CharField(max_length=500,default="Your thoughts here")
    #opinion    = models.BooleanField(default=True,null=False)
    picture    = models.ImageField(upload_to="pictures/",default="/pictures/pict.jpg")
    author     =  models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    #author     = models.CharField(max_length=100,null=False,default="guest",)

    def __str__(self):
        return self.title

class Rating(models.Model):
    blog_point = models.ForeignKey(stories , on_delete=models.CASCADE)
    rank       = models.SmallIntegerField(default=0)

    def __str__(self):
        return str(self.rank)

forms.py
from django import forms
from stories.models import stories
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class CreateForm(forms.ModelForm):

    '''title = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={'style':'max-width: 10em'}),
        required=True
    )
    description = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'style':'max-width: 15em'}),
        required=True
    )
    content = forms.CharField(
        max_length=100000,
        widget=forms.Textarea(),
    )
    author = forms.CharField(
        max_length=100,
        widget=forms.HiddenInput()
    )'''

    class Meta:
        model = stories
        fields = ('title','description','picture','content',)

class SearchForm(forms.ModelForm):

    search = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'style': 'max-width: 10em'}),
        required=True,
    )

class SignUpForm(UserCreationForm):

    email = forms.EmailField(label="Email Address")

    class Meta:

        model = User
        fields = ("email","username","password1","password2")

accounts/views.py
from django.shortcuts import render,redirect
from forms import SignUpForm
from django.views.generic import TemplateView
from django.contrib.auth import login,authenticate
from django.contrib.auth.models import User
# Create your views here.
class signupclass(TemplateView):
     def get(self,request):
         form = SignUpForm()
         return render(request,'registration/signup.html',{'form':form})

     def post(self,request):
         form = SignUpForm(request.POST)
         if form.is_valid():
             user = form.save()
             '''email = form.cleaned_data.get('email')
             username = form.cleaned_data.get('username')
             password = form.cleaned_data.get('password1')'''
             #user = User.objects.create_user(username=username,email=email,password=password)
             user.save()
             '''user = authenticate(username = username,password = password)'''
             return redirect('/')

class ProfileDisplay(TemplateView):
    def get(self,request):
        return render(request,'registration/profile.html',{})

'''class logoutConfirmation(TemplateView):
    def get(self,request):
        return render(request,'registration/logout_confirmation.html',{})'''

stories/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import TemplateView
from .models import stories,Rating
from django.core.mail import send_mail
from blogapp import settings
# Create your views here.
#from django.http import HttpResponse,Http404
from forms import CreateForm,SearchForm

def stories_view(request):
    allblogs = stories.objects.all()
    context = {'allblogs': allblogs}
    return render(request, "stories/stories.html", context)

def blog_number(request,number):

    blog = get_object_or_404(stories, id = number)
    #rank = get_object_or_404(Rating,id = number)'rank' : Rating.objects.get(id=number)
    return render(request,"stories/Details.html",{'blog' : stories.objects.get(id=number),})


def share_view(request):
    return render(request,"stories/share.html",{})

def Home_View(request):
    return render(request,"stories/Home.html",{})

class CreateBlog(TemplateView):
    TemplateName = 'stories/create.html'
    def get(self,request):
        form = CreateForm()
        return render(request,self.TemplateName,{'form' : form})
    def post(self,request):
        userinstance = stories(author = request.user)
        form = CreateForm(request.POST or None,request.FILES,instance = userinstance,)
        if form.is_valid():
            form.save(commit=True)
            title = form.cleaned_data['title']
            '''description = form.cleaned_data['description']
            content = form.cleaned_data['content']'''
            send_mail(subject="blog created!!",
                      message="congrats your post: "+title+" has been published successfully",
                      from_email="bloghost@yahoo.com",
                      recipient_list=[request.user.email],
                      fail_silently=False,
                      auth_user=settings.EMAIL_HOST_USER,
                      auth_password=settings.EMAIL_HOST_PASSWORD,
                      )
            return redirect('/stories/')
            #return redirect('stories:CreateBlog_ref')

templates/Details.html
{% extends 'base.html' %}
{% block title %} Details of {{blog}} {% endblock %}
{% block content %}
{% load stories_extras %}
<div class="container bg-light text-dark">
    <br>
    <h3><b>{{blog}}</b></h3>
    <br>
    <img src="{{blog.picture}}">
    <br><br>
    <h5>{{blog.description}}</h5>
    <br>
    <p> {{blog.content|urlize|url_target_blank}}</p>
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} Blogs {% endblock %}
    </title>
    <link rel="icon" type="image/png" href="https://i.ibb.co/sVjRZvh/colorful-star.png">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body style="background-color:#e9f0f2">
        <nav class="navbar navbar-expand-sm sticky-top navbar-light" style="background-color: #e3f2fd;">
             <a class="navbar-brand" href="/"> <img src="https://i.ibb.co/sVjRZvh/colorful-star.png" height="30" width="30"> BLOGHOST </a>
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/stories/">Read</a></li>
                <li class="nav-item"><a class="nav-link" href="/stories/create/">Create</a></li>
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
</body>
</html>

templates/stories.html
{% extends 'base.html' %}
{% block title %} Stories {% endblock %}
{% block content %}

    <div class="p-3 mb-2 bg-light text-dark">
        <h1>Welcome!!!  {{request.user}}</h1>
        {% if allblogs %}
        <div class = "card-columns">
            {% for story in allblogs %}
                <div class="card">
                    <img class="card-img-top" src="{{story.picture}}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{story.title}}</h5>
                        <p class="card-text">{{story.description}}</p>
                        <a href="{% url 'stories:blog_number_ref' story.id %}" class="btn btn-primary">visit</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
              <p>Nothing here!!</p>
        {% endif %}
    </div>

{% endblock %}

templates/stories/Details.html
{% extends 'stories/base.html' %}
{% block title %} Details of {{blog}} {% endblock %}
{% block content %}
{% load stories_extras %}
<div class="container bg-light text-dark view overlay zoom">
    <br>
    <center><h3><b>{{blog}}</b></h3></center>
    <br>
    <center><div><img src="{{blog.picture.url}}" style="width:100%"></div></center>
    <br><br>
    <h5>{{blog.description}}</h5>
    <br>
    <p> {{blog.content|urlize|url_target_blank|linebreaksbr}}</p>
</div>


{% endblock %}

templates/stories/Home.html
{% extends 'stories/base.html' %}
{% block title %} Home {% endblock %}
{% load static %}
{% block links %} <link rel="stylesheet" href="{% static 'stories/Home_tiles.css' %}" type="text/css"> {% endblock %}
{% block content %}
{% load crispy_forms_tags %}

        <div class="p-5 mb-2 bg-light text-dark " style="background-image : url('{% static 'stories/paper_back.jpg' %}')" >
            <!-- <h1>THIS IS THE HOMEPAGE!!</h1>
            <br>
            <p><a href="/stories/">click here </a>to view the blogs! </p>
            <p><a href="/stories/create">click here </a>to create a blog! </p>
            -->

            <div class="row ml-40 mt-40 ">

                <div class="col-md-3 col-lg-6">
                    <div class="box15">
                        <img src="{% static 'stories/Book.jpg' %}" alt="">
                        <div class="box-content">
                            <h3 class="title center">Read</h3>
                            <a href="/stories/" class="stretched-link"></a>
                        </div>
                    </div>

                </div>
                <div class="col-md-3 col-lg-6">
                    <div class="box15">
                        <img src="{% static 'stories/Write.jpg' %}" alt="">
                        <div class="box-content">
                            <h3 class="title center">Write</h3>
                            <a href="/stories/create/" class="stretched-link"></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

{% endblock %}

templates/stories/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} Blogs {% endblock %}
    </title>
    {% block links %} {% endblock %}

    <link rel="icon" type="image/png" href="https://i.ibb.co/sVjRZvh/colorful-star.png">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<!-- style="background-color:#e9f0f2" https://i.ibb.co/sVjRZvh/colorful-star.png-->
<body background="{% static 'stories/paper_back.jpg' %}">
        <nav class="navbar navbar-expand-sm sticky-top navbar-light" style="background-color: #fafcff;">
             <a class="navbar-brand" href="/"> <img src="https://i.ibb.co/sVjRZvh/colorful-star.png" height="30" width="30"> BLOGHOST </a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/stories/">Read</a></li>
                <li class="nav-item"><a class="nav-link" href="/stories/create/">Create</a></li>
            </ul>
             <ul class="navbar-nav ml-auto">
                <!-- <li class="nav-item"><a class="nav-link" href="#"> Login </a></li> -->
                 <li class="nav-item">

                     {% if user.is_authenticated %}

                            <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                            {{user.username}}
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="/accounts/profile/">Profile</a>
                                        <a class="dropdown-item" href="/accounts/logout/" onclick="alert('logged out successfully!')">logout</a>
                                    </div>
                            </div>

                     {% else %}
                            <a href="/accounts/login/" class="btn btn-outline-success" role="button">login</a>
                     {% endif %}
                 </li>
             </ul>
        </div>
        </nav>

        {% block content %}
        {% endblock %}
</body>
</html>

templates/stories/create.html
{% extends 'stories/base.html' %}
{% block title %} Pen a Blog {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated %}
        <br>
            <div class="container bg-light text-dark">

                <h1 align="center"> WRITE DOWN YOUR BLOG!! </h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-success">Publish</button>
                </form>
                <br>
            </div>
{% else %}
    <br><br>
    <div class="container bg-light text-dark">
            <p align="center"><b>Please log-in to write a blog!</b> </p>
            <center><a href="/accounts/login/" class="btn btn-success" role="button">login</a></center>
    </div>

{% endif %}
{% endblock %}

templates/stories/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Share</title>
</head>
<body>
        <p>share page</p>
        <p>{{ request.user.email }}</p>
</body>
</html>

templates/stories/stories.html
{% extends 'stories/base.html' %}
{% block title %} Stories {% endblock %}
{% block content %}

    <div class="p-3 mb-2 bg-light text-dark">
        {% if allblogs %}
        <div class="container">
            <div class = "card-columns" >

            {% for story in allblogs %}
                <!--  -->
                    <div class="card " >

                    <img class="card-img-top" src="{{story.picture.url}}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title" align="center">{{story.title}}</h5>
                        <p class="card-text">{{story.description}}</p>
                        <p class="card-text"><small class="text-muted">written by <b>{{story.author.username}}</b></small> </p>
                    </div>
                    <a href="{% url 'stories:blog_number_ref' story.id %}" class="stretched-link"></a>
                </div>
                </a>
            {% endfor %}
        </div>
        {% else %}
              <p>Nothing here!!</p>
        {% endif %}</div>

    </div>

{% endblock %}
<!--Zoom effect-->
<!-- <div class="view overlay zoom">
    <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/6-col/img%20(131).jpg" class="img-fluid " alt="smaple image">
    <div class="mask flex-center">
        <p class="white-text">Zoom effect</p>
    </div>
</div> -->